/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export type ForkDestination = {
  /** name of the destination */
  name?: string;
  /** tag of the fork */
  tag?: string;
  /** url of the destination */
  url?: string;
};
