/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of Fork e.g. approved, rejected
 */
export type ForkStatus = typeof ForkStatus[keyof typeof ForkStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ForkStatus = {
  requested: 'requested',
  approved: 'approved',
  rejected: 'rejected',
} as const;
