/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { ForkDestination } from './forkDestination';
import type { ForkOrigin } from './forkOrigin';
import type { ForkStatus } from './forkStatus';

export interface Fork {
  /** date of fork request */
  date: string;
  destination: ForkDestination;
  /** name of the fork */
  name: string;
  origin: ForkOrigin;
  /** URL of Fork request */
  request_url: string;
  /** Status of Fork e.g. approved, rejected */
  status: ForkStatus;
}
