/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetMatchTermsParams = {
filters?: {
  /** A property to filter results by */
  attribute?: string;
  /** Condition for filter attribute */
  condition?: string;
  /** The value for the filter specified above */
  value?: number;
};
};
