/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export type GetMatchTermsParams = {
/**
 * A property to filter results by
 */
filter?: string;
/**
 * The value for the filter specified above
 */
value?: string;
};
