/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface Ontology {
  description: string;
  /** Unique identifier */
  id: string;
  imports: string[][];
  name: string;
  url: string;
  version_info: string;
}
