/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

/**
 * Terms
 */
export type OrganizationTerms = { [key: string]: any };
