/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface Organization {
  /** Description of Organization */
  description: string;
  /** Organization uri for icon */
  icon?: string;
  /** Unique identifier of organization */
  id: string;
  name: string;
  /** Organization uri */
  url: string;
}
