/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export type PatchTerm200 = {
  /** Response status */
  status?: string;
  /** Patched term */
  term?: unknown;
};
