/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SearchElasticBodyQuery } from './searchElasticBodyQuery';

export type SearchElasticBody = {
  /** Starting index */
  from?: number;
  /** ElasticSearch query */
  query?: SearchElasticBodyQuery;
  /** Number of results to return */
  size?: number;
};
