/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { SearchElastic200ResultsItem } from './searchElastic200ResultsItem';

export type SearchElastic200 = {
  results?: SearchElastic200ResultsItem[];
};
