/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { TermContext } from './termContext';
import type { TermGraphItemItem } from './termGraphItemItem';

export interface Term {
  '@context': TermContext;
  '@graph'?: TermGraphItemItem[][];
}
