/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** Total Actions */
  actions?: string;
  /** active user or not */
  active?: boolean;
  /** Date User was created */
  creationDate: string;
  /** Email */
  email: string;
  /** Unique identifier */
  id?: string;
  /** Date User was last login */
  last_login?: string;
  /** Last Name */
  lastName: string;
  /** My Merge Reviews */
  merge_reviews?: unknown;
  /** Name */
  name: string;
  /** ORCID ID */
  orcid?: string;
  /** organization */
  organization: string;
  /** My Organizations */
  organizations?: unknown;
  /** Password */
  password: string;
  /** User Role */
  role: string;
  /** My Term Variants */
  term_variants?: unknown;
  /** UserName */
  username?: string;
}
