/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VariantEditingUser } from './variantEditingUser';
import type { VariantOriginatingUser } from './variantOriginatingUser';

export interface Variant {
  description: string;
  editingUser: VariantEditingUser;
  id?: string;
  organization: string;
  originatingUser: VariantOriginatingUser;
  status: string;
  timestamp: string;
  url: string;
}
