/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { VersionFork } from './versionFork';

export interface Version {
  action: string;
  author: string;
  fork: VersionFork;
  id: string;
  lastModifyBy: string;
}
