FROM node:20

WORKDIR /home/pptruser/test

COPY interlex/test/package.json .
COPY interlex/test/package-lock.json .
RUN ls -l /home/pptruser/test && cat /home/pptruser/test/package-lock.json
RUN npm ci

COPY . .

USER node


