FROM ghcr.io/puppeteer/puppeteer:latest

USER pptruser

WORKDIR /home/pptruser/test

COPY interlex/test/package.json .
COPY interlex/test/package-lock.json .

RUN npm ci

COPY --chown=pptruser:pptruser interlex/test .


