apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: 'letsencrypt-interlex'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: filippo@metacell.us
    privateKeySecretRef:
      name: letsencrypt-interlex
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/1/elastic/Interlex_pr/_search
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;
  name: interlex-nginx-ingress
spec:
  rules:
  - host: "interlex.dev.metacell.us"
    http:
      paths:
      - path: /api/elasticsearch
        pathType: Prefix
        backend:
          service:
            name: interlex
            port:
              number: 80
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: interlex
            port:
              number: 80
  tls:
  - hosts:
    - "interlex.dev.metacell.us"
    secretName: interlex-tls
