apiVersion: cert-manager.io/v1
kind: Issuer 
metadata:
  name: 'letsencrypt-interlex'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: filippo@metacell.us
    privateKeySecretRef:
      name: letsencrypt-interlex
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt-interlex
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/proxy-method: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: *";
      more_set_headers "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: Content-Type, Authorization";
  name: interlex-nginx-ingress
spec:
  rules:
  - host: "{{DOMAIN}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: interlex
            port:
              number: 80
      - path: /api/elasticsearch
        pathType: Prefix
        backend:
          service:
            name: interlex
            port:
              number: 3001
  tls:
  - hosts:
    - "{{DOMAIN}}"
    secretName: interlex-tls
