apiVersion: apps/v1
kind: Deployment
metadata:
  name: interlex
spec:
  selector:
    matchLabels:
      app: interlex
  replicas: 1
  template:
    metadata:
      labels:
        app: interlex
    spec:
      containers:
        - name: interlex
          image: "gcr.io/metacellllc/interlex:{{CF_SHORT_REVISION}}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 1500m
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: interlex
spec:
  type: ClusterIP
  ports:
    - name : http
      port: 80
      targetPort: 80
    - name : elastic
      port: 3001
      targetPort: 3001
  selector:
    app: interlex