apiVersion: apps/v1
kind: Deployment
metadata:
  name: interlex
spec:
  selector:
    matchLabels:
      app: interlex
  replicas: 1
  template:
    metadata:
      labels:
        app: interlex
    spec:
      containers:
        - name: interlex
          image: "gcr.io/metacellllc/interlex:{{CF_SHORT_REVISION}}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1500m
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 768Mi
          command: [ "node", "server.js" ]
---
apiVersion: v1
kind: Service
metadata:
  name: interlex
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
    - port: 3000
      targetPort: 3000
  selector:
    app: interlex