/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * InterLex URI structure API
 * Resolution, update, and compare for ontologies and ontology identifiers.
 * OpenAPI spec version: 0.0.1
 */

export * from './maskErrorResponse';
export * from './parseErrorResponse';