/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { Ontology } from './ontology';
import type { Terms } from './terms';

export interface Organization {
  /** author */
  author: string;
  /** Date organization was created */
  creation_date: string;
  /** Description of Organization */
  description: string;
  /** Unique identifier */
  id: string;
  /** legal name */
  legalName?: string;
  name: string;
  /** Ontology */
  ontologies?: Ontology[];
  /** review aspect */
  reviewAspect?: string;
  /** Terms */
  terms?: Terms[];
  /** Organization uri */
  url: string;
}
