import {Box, Typography} from "@mui/material";
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';
import openDataCommons from '../../Icons/svg/openDataCommons.svg';
import drugDesign from '../../Icons/svg/drugDesign.svg';
import NIDM from '../../Icons/svg/NIDM.svg';
import NIF from '../../Icons/svg/NIF.svg';
import NIDDK from '../../Icons/svg/NIDDK.svg';
import SPARC from '../../Icons/svg/SPARC.svg';
import RRID from '../../Icons/svg/RRID.svg';
import {vars} from "../../theme/variables";
import Link from "@mui/material/Link";

const {gray700, gray500, gray200} = vars

const organizationsList = [
  {
    logo: openDataCommons,
    title: 'Open Data Commons for Traumatic Brain Injury',
    description: 'The ODC-TBI accelerates progress in pre-clinical TBI research through sharing and re-using data generated by the ODC-TBI community, and promoting transparency, rigor and reproducibility in pre-clinical TBI research.\n' +
      'A free community platform to Share Data, Publish Data with a DOI, and get Citations.',
    link: 'https://odc-tbi.org'
  },
  {
    logo: drugDesign,
    title: 'Drug Design Data Resource',
    description: 'An open resource to advance computer-aided drug discovery through the interchange of high quality protein-ligand datasets, workflows and community-wide blind data challenges',
    link: 'https://drugdesigndata.org'
  },
  {
    logo: NIDDK,
    title: 'NIDDK Information Network',
    description: 'dkNET provides a catalog of resources important to research on kidney, urologic, hematologic, digestive, metabolic and endocrine diseases, diabetes and nutrition',
    link: 'https://dknet.org'
  },
  {
    logo: NIDM,
    title: 'NIDM Terminology',
    description: 'NIDM Terminology',
    link: ''
  },
  {
    logo: NIF,
    title: 'Neuroscience Information Framework',
    description: 'The Neuroscience Information Framework is a dynamic inventory of Web-based neuroscience resources: data, materials, and tools accessible via any computer connected to the Internet. An initiative of the NIH Blueprint for Neuroscience Research, NIF advances neuroscience research by enabling discovery and access to public research data and tools worldwide through an open source, networked environment.',
    link: 'https://neuinfo.org'
  },
  {
    logo: RRID,
    title: 'RRID Portal',
    description: 'This is the Resource Identification Portal, supporting guidelines for Rigor and Transparency in scientific publications. If you are an author, please find your key resources: Antibodies, Model Organisms, Cell Lines, Plasmids, and other Tools (software, databases, services). Just copy the RRID citation into your paper. If you can\'t find your resource add a new one, we make it easy (big green button on the bottom of this page).',
    link: ''
  },
  {
    logo: SPARC,
    title: 'SPARC Anatomical Working Group',
    description: 'The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) drive to map out the neural circuitry responsible for visceral control in higher vertebrates. The SPARC Anatomy Working Group (SAWG) is responsible for the integrity of anatomical knowledge in SPARC. In particular, it provides the relevant guidance and expertise about: Defining and naming anatomical terms, Maintaining ontologies of anatomical knowledge, Compiling and curating computable knowledge about multiscale routes pathways',
    link: 'https://sparc.science/help/59wrnT6knb7KuGPJeNgT8k'
  }
]
const Organizations = () => {
  return(
    <Box p='2.25rem 5rem' flexGrow={1} overflow='auto'>
      <Typography fontSize='1.5rem' color={gray700} fontWeight={600} mb='1.5rem'>{organizationsList.length} Organizations</Typography>
      <List sx={{
        width: '100%',
        padding: 0,
        '& .MuiListItem-root': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'flex-start',
          padding: '1.5rem',
          gap: '1rem',
          borderBottom: `1px solid ${gray200}`
        },
        '& .MuiListItemText-root': {
          margin: 0,
          display: 'flex',
          flexDirection: 'column',
          gap: '1rem',
          width: '100%',
          
          '& .MuiListItemText-primary': {
            '& .MuiTypography-root': {
              color: gray700,
              fontSize: '1.25rem',
              fontWeight: 500
            },
            '& .MuiLink-root': {
              textDecoration: 'none',
              color: gray500,
              fontSize: '1.125rem',
              fontWeight: 500,
            }
          },
          
          '& .MuiListItemText-secondary': {
            color: gray500,
            fontSize: '0.875rem',
            fontWeight: 400,
          }
          
        }
      }}>
        {
          organizationsList.map((organization, index) => <ListItem key={index}>
            <img src={organization.logo} alt="openDataCommons" />
            <ListItemText primary={
              <Box display='flex' alignItems='center' justifyContent='space-between'>
                <Typography component='span'>{organization.title}</Typography>
                <Link href={organization.link} display='flex'>
                  {organization.link}
                </Link>
              
              </Box>
            } secondary={organization.description} />
          </ListItem>)
        }
       
       
      </List>
    </Box>
  )
}

export default Organizations