version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
  - "e2e_test"

steps:
  clone:
    stage: "clone"
    title: "Cloning interlex"
    type: "git-clone"
    repo: "metacell/interlex"
    revision: "${{CF_BRANCH}}"

  build:
    stage: "build"
    title: "Building interlex"
    type: "build"
    image_name: "interlex"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
    working_directory: ./interlex
    buildkit: true
    registry: "${{CODEFRESH_REGISTRY}}"
    build_arguments:
      - VITE_API_URL=${{VITE_API_URL}}
      - VITE_SCICRUNCH_API_KEY=${{VITE_SCICRUNCH_API_KEY}}

  deploy:
    stage: "deploy"
    title: "Deploying interlex"
    image: codefresh/cf-deploy-kubernetes
    tag: latest
    working_directory: ./interlex/deploy/k8s
    commands:
      - /cf-deploy-kubernetes interlex.yaml
      - /cf-deploy-kubernetes ingress.yaml
    environment:
      - KUBECONTEXT=${{CLUSTER_NAME}}
      - KUBERNETES_NAMESPACE=${{NAMESPACE}}
  test_build:
    stage: "e2e_test"
    type: build
    title: Building ILEX test image
    image_name: ilex-test
    dockerfile: Dockerfile.testing
    buildkit: true
    registry: ${{REGISTRY}}
  e2e_test:
    type: composition
    title: Running E2E Tests
    stage: e2e_test
    working_directory: ./interlex/test
    composition:
      version: '2'
      services:
        app:
          image: '${{build}}'
    composition_candidates:
      test:
        image: '${{test_build}}'
        links:
          - app
        working_dir: /home/pptruser
        environment:
          - TEST_USERNAME=${{TEST_USERNAME}}
          - TEST_PASSWORD=${{TEST_PASSWORD}}
        command: bash -c 'npm ci && npm test create && npm test userInfo && npm test searchInfo'
