server {
    listen 80;

    location / {
        root   /usr/share/nginx/html/;
        try_files $uri /index.html;
    }

    # Proxy for Elasticsearch API requests
    location /api/elasticsearch {
        proxy_pass https://scicrunch.org/api/1/elastic/Interlex_pr/_search;
        proxy_set_header Host scicrunch.org;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Content-Type application/json;
        proxy_ssl_verify off;
    }

    location ~ ^/u/ops/.* {
        proxy_pass https://uri.olympiangods.org;
        proxy_set_header Host uri.olympiangods.org;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_verify off;
    }

    location /static/ {
        autoindex on;
        alias /usr/share/nginx/html/static/;
    }
}
