/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { Organization } from './organization';

export type Organizations = Organization[];
