/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { TermPrefixes } from './termPrefixes';

export interface Term {
  description: string;
  /** Unique identifier */
  id: string;
  name: string;
  prefixes: TermPrefixes;
  triples: string[][];
}
