/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type { UserNameItem } from './userNameItem';

export interface User {
  /** Total Actions */
  actions: string;
  /** active user or not */
  active?: boolean;
  /** Date User was created */
  creation_date: string;
  /** Email */
  email: string;
  /** Unique identifier */
  id: string;
  /** ORCID ID */
  identifier?: string;
  /** Date User was last login */
  last_login?: string;
  /** My Merge Reviews */
  merge_reviews: unknown;
  /** Object that specify given and family name */
  name: UserNameItem[];
  /** My Organizations */
  organizations: unknown;
  /** User Role */
  role: string;
  /** My Term Variants */
  term_variants: unknown;
}
