/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * InterLex URI structure API
 * Resolution, update, and compare for ontologies and ontology identifiers.
 * OpenAPI spec version: 0.0.1
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw'

export const getGetEndpointsCuriesResponseMock = () => ((() => {
  return [{
    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    rdfs: "http://www.w3.org/2000/01/rdf-schema#",
    owl: "http://www.w3.org/2002/07/owl#"
  }];
})())

export const getGetOntologiesOntologiesResponseMock = () => ((() => ({
                status_code: 200,
                message: ""
              }))())

export const getGetEndpointsIlxResponseMock = () => ((() => {
  return {
    "@context": {
      "owl": "http://www.w3.org/2002/07/owl#",
      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    },
    "@graph": [
      {
        "@id": "http://uri.interlex.org/base/ilx_0101431",
        "http://uri.interlex.org/tgbugs/uris/readable/hasIlxId": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "http://uri.interlex.org/tgbugs/uris/readable/hasIlxPreferredId": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "http://uri.interlex.org/tgbugs/uris/readable/owlEquivalent": "owlEquivalent",
        "http://uri.interlex.org/tgbugs/uris/readable/lastModify": "lastModify",
        "http://uri.interlex.org/tgbugs/uris/readable/lastModifyBy": "lastModifyBy",
        "http://uri.interlex.org/tgbugs/uris/readable/submittedBy": "submittedBy"
      },
      {
        "@id": "http://uri.interlex.org/base/ontologies/ilx_0101431",
        "@type": "owl:Ontology",
        "http://purl.obolibrary.org/obo/IAO_0000136": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "owl:versionIRI": {
          "@id": "http://uri.interlex.org/base/ontologies/ilx_0101431/version/1717611398/ilx_0101431"
        },
        "owl:versionInfo": "2024-06-05T18:16:38,089335Z",
        "rdfs:comment": "InterLex single term result for base/ilx_0101431 at 2024-06-05T18:16:38,089335Z"
      },
      {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0000955",
        "@type": "owl:Class",
        "http://purl.obolibrary.org/obo/IAO_0000115": "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
        "http://uri.interlex.org/base/ilx_0112784": {
          "@id": "http://uri.interlex.org/base/ilx_0102661"
        },
        "http://uri.interlex.org/base/ilx_0112785": {
          "@id": "http://uri.interlex.org/base/ilx_0101999"
        },
        "http://uri.interlex.org/base/ilx_0112796": {
          "@id": "http://uri.interlex.org/base/ilx_0101901"
        },
        "http://uri.interlex.org/base/readable/synonym": [
          "Encephalon",
          "synganglion",
          "the brain",
          "suprasegmental levels of nervous system",
          "suprasegmental structures"
        ],
        "http://uri.interlex.org/tgbugs/uris/readable/MISSING_ILX_ID": true,
        "http://uri.interlex.org/tgbugs/uris/readable/hasExistingId": [
          {
            "@id": "http://uri.neuinfo.org/nif/nifstd/birnlex_796"
          },
          {
            "@id": "http://purl.org/sig/ont/fma/fma50801"
          },
          {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0000955"
          }
        ],
        "rdfs:label": "Brain",
        "rdfs:subClassOf": {
          "@id": "http://uri.interlex.org/base/ilx_0108124"
        }
      }
    ]
  };
})())

export const getGetEndpointsIlxGetResponseMock = () => ((() => {
  return {
    "@context": {
      "owl": "http://www.w3.org/2002/07/owl#",
      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    },
    "@graph": [
      {
        "@id": "http://uri.interlex.org/base/ilx_0101431",
        "http://uri.interlex.org/tgbugs/uris/readable/hasIlxId": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "http://uri.interlex.org/tgbugs/uris/readable/hasIlxPreferredId": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "http://uri.interlex.org/tgbugs/uris/readable/owlEquivalent": "owlEquivalent",
        "http://uri.interlex.org/tgbugs/uris/readable/lastModify": "lastModify",
        "http://uri.interlex.org/tgbugs/uris/readable/lastModifyBy": "lastModifyBy",
        "http://uri.interlex.org/tgbugs/uris/readable/submittedBy": "submittedBy"
      },
      {
        "@id": "http://uri.interlex.org/base/ontologies/ilx_0101431",
        "@type": "owl:Ontology",
        "http://purl.obolibrary.org/obo/IAO_0000136": {
          "@id": "http://uri.interlex.org/base/ilx_0101431"
        },
        "owl:versionIRI": {
          "@id": "http://uri.interlex.org/base/ontologies/ilx_0101431/version/1717611398/ilx_0101431"
        },
        "owl:versionInfo": "2024-06-05T18:16:38,089335Z",
        "rdfs:comment": "InterLex single term result for base/ilx_0101431 at 2024-06-05T18:16:38,089335Z"
      },
      {
        "@id": "http://purl.obolibrary.org/obo/UBERON_0000955",
        "@type": "owl:Class",
        "http://purl.obolibrary.org/obo/IAO_0000115": "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
        "http://uri.interlex.org/base/ilx_0112784": {
          "@id": "http://uri.interlex.org/base/ilx_0102661"
        },
        "http://uri.interlex.org/base/ilx_0112785": {
          "@id": "http://uri.interlex.org/base/ilx_0101999"
        },
        "http://uri.interlex.org/base/ilx_0112796": {
          "@id": "http://uri.interlex.org/base/ilx_0101901"
        },
        "http://uri.interlex.org/base/readable/synonym": [
          "Encephalon",
          "synganglion",
          "the brain",
          "suprasegmental levels of nervous system",
          "suprasegmental structures"
        ],
        "http://uri.interlex.org/tgbugs/uris/readable/MISSING_ILX_ID": true,
        "http://uri.interlex.org/tgbugs/uris/readable/hasExistingId": [
          {
            "@id": "http://uri.neuinfo.org/nif/nifstd/birnlex_796"
          },
          {
            "@id": "http://purl.org/sig/ont/fma/fma50801"
          },
          {
            "@id": "http://purl.obolibrary.org/obo/UBERON_0000955"
          }
        ],
        "rdfs:label": "Brain",
        "rdfs:subClassOf": {
          "@id": "http://uri.interlex.org/base/ilx_0108124"
        }
      }
    ]
  };
})())


export const getGetEndpointsOpsMockHandler = () => {
  return http.get('*/Operations/:group/ops/:operation', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostEndpointsOpsMockHandler = () => {
  return http.post('*/Operations/:group/ops/:operation', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsPrivMockHandler = () => {
  return http.get('*/Privileged endpoints/:group/priv/:page', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostEndpointsPrivMockHandler = () => {
  return http.post('*/Privileged endpoints/:group/priv/:page', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsContributionsMockHandler = () => {
  return http.get('*/:group/contributions/interlex', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsCuriesMockHandler = (overrideResponse?: void) => {
  return http.get('*/:group/curies/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetEndpointsCuriesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostEndpointsCuriesMockHandler = () => {
  return http.post('*/:group/curies/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getGetDiffCuriesMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/curies/:prefixIriCurie', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffLexicalMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/lexical/:label', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesContributionsMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/contributions', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesUrisMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/uris/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesUrisVersionMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/uris/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesVersionMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffOntologiesIlxMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/ontologies/:fragPrefId.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffReadableMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffUrisMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffVersionsCuriesMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/versions/:epochVerstrId/curies/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffVersionsReadableMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/versions/:epochVerstrId/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffVersionsUrisMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/versions/:epochVerstrId/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffVersionsIlxMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/versions/:epochVerstrId/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetDiffIlxMockHandler = () => {
  return http.get('*/:group/diff/:otherGroupDiff/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsMappedMockHandler = () => {
  return http.get('*/:group/external/mapped', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostEndpointsMappedMockHandler = () => {
  return http.post('*/:group/external/mapped', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsLexicalMockHandler = () => {
  return http.get('*/:group/lexical/:label', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesContributionsMockHandler = () => {
  return http.get('*/:group/ontologies/contributions', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesUrisMockHandler = () => {
  return http.get('*/:group/ontologies/uris/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOntologiesOntologiesUrisMockHandler = () => {
  return http.post('*/:group/ontologies/uris/:ontPath/:filename.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesUrisVersionMockHandler = () => {
  return http.get('*/:group/ontologies/uris/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOntologiesOntologiesUrisVersionMockHandler = () => {
  return http.post('*/:group/ontologies/uris/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesMockHandler = (overrideResponse?: void) => {
  return http.get('*/:group/ontologies/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetOntologiesOntologiesResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOntologiesOntologiesMockHandler = () => {
  return http.post('*/:group/ontologies/:ontPath/:filename.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesVersionMockHandler = () => {
  return http.get('*/:group/ontologies/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOntologiesOntologiesIlxMockHandler = () => {
  return http.get('*/:group/ontologies/:fragPrefId.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOwnCuriesMockHandler = () => {
  return http.post('*/:group/own/:otherGroup/curies/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnCuriesMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/curies/:prefixIriCurie', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesContributionsMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/contributions', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesUrisMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/uris/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOwnOntologiesUrisMockHandler = () => {
  return http.post('*/:group/own/:otherGroup/ontologies/uris/:ontPath/:filename.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesUrisVersionMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/uris/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOwnOntologiesUrisVersionMockHandler = () => {
  return http.post('*/:group/own/:otherGroup/ontologies/uris/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/:ontPath/:filename/', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostOwnOntologiesMockHandler = () => {
  return http.post('*/:group/own/:otherGroup/ontologies/:ontPath/:filename.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesVersionMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/:ontPath/:filename/version/:epochVerstrOnt/:filenameTerminal.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnOntologiesIlxMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/ontologies/:fragPrefId.:extension', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnUrisMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnVersionsCuriesMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/versions/:epochVerstrId/curies/:prefixIriCurie', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnVersionsReadableMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/versions/:epochVerstrId/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnVersionsUrisMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/versions/:epochVerstrId/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOwnVersionsIlxMockHandler = () => {
  return http.get('*/:group/own/:otherGroup/versions/:epochVerstrId/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsProvMockHandler = () => {
  return http.get('*/:group/prov/identities/:identity', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsReadableMockHandler = () => {
  return http.get('*/:group/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPatchEndpointsReadableMockHandler = () => {
  return http.patch('*/:group/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPostEndpointsUploadMockHandler = () => {
  return http.post('*/:group/upload', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsUrisMockHandler = () => {
  return http.get('*/:group/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetVersionsCuriesMockHandler = () => {
  return http.get('*/:group/versions/:epochVerstrId/curies/:prefixIriCurie', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetVersionsReadableMockHandler = () => {
  return http.get('*/:group/versions/:epochVerstrId/readable/:word', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetVersionsUrisMockHandler = () => {
  return http.get('*/:group/versions/:epochVerstrId/uris/:uriPath', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetVersionsIlxMockHandler = () => {
  return http.get('*/:group/versions/:epochVerstrId/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsIlxMockHandler = (overrideResponse?: void) => {
  return http.get('*/:group/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetEndpointsIlxResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getPatchEndpointsIlxMockHandler = () => {
  return http.patch('*/:group/:fragPrefId', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetEndpointsIlxGetMockHandler = (overrideResponse?: void) => {
  return http.get('*/:group/:fragPrefId.:extension', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetEndpointsIlxGetResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getInterLexURIStructureAPIMock = () => [
  getGetEndpointsOpsMockHandler(),
  getPostEndpointsOpsMockHandler(),
  getGetEndpointsPrivMockHandler(),
  getPostEndpointsPrivMockHandler(),
  getGetEndpointsContributionsMockHandler(),
  getGetEndpointsContributionsMockHandler(),
  getGetEndpointsCuriesMockHandler(),
  getPostEndpointsCuriesMockHandler(),
  getGetEndpointsCuriesMockHandler(),
  getGetDiffCuriesMockHandler(),
  getGetDiffCuriesMockHandler(),
  getGetDiffLexicalMockHandler(),
  getGetDiffOntologiesContributionsMockHandler(),
  getGetDiffOntologiesUrisMockHandler(),
  getGetDiffOntologiesUrisVersionMockHandler(),
  getGetDiffOntologiesMockHandler(),
  getGetDiffOntologiesVersionMockHandler(),
  getGetDiffOntologiesIlxMockHandler(),
  getGetDiffReadableMockHandler(),
  getGetDiffUrisMockHandler(),
  getGetDiffVersionsCuriesMockHandler(),
  getGetDiffVersionsCuriesMockHandler(),
  getGetDiffVersionsReadableMockHandler(),
  getGetDiffVersionsUrisMockHandler(),
  getGetDiffVersionsIlxMockHandler(),
  getGetDiffIlxMockHandler(),
  getGetEndpointsMappedMockHandler(),
  getPostEndpointsMappedMockHandler(),
  getGetEndpointsLexicalMockHandler(),
  getGetOntologiesOntologiesContributionsMockHandler(),
  getGetOntologiesOntologiesUrisMockHandler(),
  getPostOntologiesOntologiesUrisMockHandler(),
  getGetOntologiesOntologiesUrisVersionMockHandler(),
  getPostOntologiesOntologiesUrisVersionMockHandler(),
  getGetOntologiesOntologiesMockHandler(),
  getPostOntologiesOntologiesMockHandler(),
  getGetOntologiesOntologiesVersionMockHandler(),
  getGetOntologiesOntologiesIlxMockHandler(),
  getGetOwnCuriesMockHandler(),
  getPostOwnCuriesMockHandler(),
  getGetOwnCuriesMockHandler(),
  getGetOwnOntologiesContributionsMockHandler(),
  getGetOwnOntologiesUrisMockHandler(),
  getPostOwnOntologiesUrisMockHandler(),
  getGetOwnOntologiesUrisVersionMockHandler(),
  getPostOwnOntologiesUrisVersionMockHandler(),
  getGetOwnOntologiesMockHandler(),
  getPostOwnOntologiesMockHandler(),
  getGetOwnOntologiesVersionMockHandler(),
  getGetOwnOntologiesIlxMockHandler(),
  getGetOwnUrisMockHandler(),
  getGetOwnVersionsCuriesMockHandler(),
  getGetOwnVersionsCuriesMockHandler(),
  getGetOwnVersionsReadableMockHandler(),
  getGetOwnVersionsUrisMockHandler(),
  getGetOwnVersionsIlxMockHandler(),
  getGetEndpointsProvMockHandler(),
  getGetEndpointsReadableMockHandler(),
  getPatchEndpointsReadableMockHandler(),
  getPostEndpointsUploadMockHandler(),
  getGetEndpointsUrisMockHandler(),
  getGetVersionsCuriesMockHandler(),
  getGetVersionsCuriesMockHandler(),
  getGetVersionsReadableMockHandler(),
  getGetVersionsUrisMockHandler(),
  getGetVersionsIlxMockHandler(),
  getGetEndpointsIlxMockHandler(),
  getPatchEndpointsIlxMockHandler(),
  getGetEndpointsIlxGetMockHandler()]
