/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddToDiscussion200,
  Curies,
  Discussion,
  Discussions,
  Forks,
  GetMatchTermsParams,
  Hierarchies,
  Ontologies,
  Organization,
  Organizations,
  PatchTerm200,
  Term,
  Terms,
  User,
  Variants,
  Versions
} from '../../model/backend'
import { customInstance } from '../../../mock/mutator/customClient';
import type { BodyType } from '../../../mock/mutator/customClient';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * @summary Log in to OpenAPI space
 */
export const login = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/operations/login`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Log out from OpenAPI space
 */
export const logout = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/operations/logout`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Register to OpenAPI space
 */
export const register = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/operations/signup`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Used to retrieve a specific user.
 */
export const getUser = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<User>(
      {url: `/operations/getUser/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to retrieve a specific user's terms.
 */
export const getUserTerms = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Terms>(
      {url: `/operations/getUser/${id}/terms`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to retrieve a specific user's organizations.
 */
export const getUserOrganizations = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Organizations>(
      {url: `/operations/getUser/${id}/organizations`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to retrieve a specific user's forks.
 */
export const getUserForks = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Forks>(
      {url: `/operations/getUser/${id}/forks`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to retrieve a specific organization.
 */
export const getOrganization = (
    id: string,
    organization: BodyType<Organization>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Organization>(
      {url: `/operations/getOrganization/${id}`, method: 'GET',
      headers: {'Content-Type': 'application/json', }
    },
      options);
    }
  
/**
 * @summary Used to save a new organization.
 */
export const newOrganization = (
    organization: BodyType<Organization>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Organization>(
      {url: `/operations/newOrganization`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: organization
    },
      options);
    }
  
/**
 * @summary Get all organizations
 */
export const getOrganizations = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Organizations>(
      {url: `/operations/getOrganizations`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Get all terms for this organization
 */
export const getOrganizationsTerms = (
    organization: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Terms>(
      {url: `/operations/getOrganization/${organization}/terms`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Get all ontologies for this organization
 */
export const getOrganizationsOntologies = (
    organization: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Ontologies>(
      {url: `/operations/getOrganization/${organization}/ontologies`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Get all curies for this organization
 */
export const getOrganizationsCuries = (
    organization: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Curies>(
      {url: `/operations/getOrganization/${organization}/curies`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Retrieve hierarchy results
 */
export const getHierarchyResults = (
    group: string,
    property: string,
    start: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Hierarchies>(
      {url: `/${group}/query/transitive/${property}/${start}?depth`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to save a term.
 */
export const patchTerm = (
    group: string,
    fragPrefId: string,
    term: BodyType<Term>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<PatchTerm200>(
      {url: `/${group}/${fragPrefId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: term
    },
      options);
    }
  
/**
 * @summary List all matching terms
 */
export const getMatchTerms = (
    group: string,
    term: string,
    params?: GetMatchTermsParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Terms>(
      {url: `/${group}/search/${term}`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary List all curies for group
 */
export const getCuries = (
    group: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Curies>(
      {url: `/${group}/curies`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary List all variants for a term
 */
export const getVariants = (
    group: string,
    term: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Variants>(
      {url: `/${group}/variants/${term}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary List all versions for a term
 */
export const getVersions = (
    group: string,
    term: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Versions>(
      {url: `/${group}/versions/${term}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary List all ontologies
 */
export const getOntologies = (
    group: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Ontologies>(
      {url: `/${group}/ontologies`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary List all ontologies
 */
export const getTermOntologies = (
    group: string,
    term: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Ontologies>(
      {url: `/${group}/ontologies/${term}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary List all discussions for a term
 */
export const getDiscussions = (
    group: string,
    term: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<Discussions>(
      {url: `/${group}/discussions/${term}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Used to save a new discussion.
 */
export const addToDiscussion = (
    group: string,
    term: string,
    discussion: BodyType<Discussion>,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<AddToDiscussion200>(
      {url: `/${group}/add_discussions/${term}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: discussion
    },
      options);
    }
  
/**
 * @summary Checks if the server is running
 */
export const getPing = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/ping`, method: 'GET'
    },
      options);
    }
  

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type RegisterResult = NonNullable<Awaited<ReturnType<typeof register>>>
export type GetUserResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserTermsResult = NonNullable<Awaited<ReturnType<typeof getUserTerms>>>
export type GetUserOrganizationsResult = NonNullable<Awaited<ReturnType<typeof getUserOrganizations>>>
export type GetUserForksResult = NonNullable<Awaited<ReturnType<typeof getUserForks>>>
export type GetOrganizationResult = NonNullable<Awaited<ReturnType<typeof getOrganization>>>
export type NewOrganizationResult = NonNullable<Awaited<ReturnType<typeof newOrganization>>>
export type GetOrganizationsResult = NonNullable<Awaited<ReturnType<typeof getOrganizations>>>
export type GetOrganizationsTermsResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsTerms>>>
export type GetOrganizationsOntologiesResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsOntologies>>>
export type GetOrganizationsCuriesResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsCuries>>>
export type GetHierarchyResultsResult = NonNullable<Awaited<ReturnType<typeof getHierarchyResults>>>
export type PatchTermResult = NonNullable<Awaited<ReturnType<typeof patchTerm>>>
export type GetMatchTermsResult = NonNullable<Awaited<ReturnType<typeof getMatchTerms>>>
export type GetCuriesResult = NonNullable<Awaited<ReturnType<typeof getCuries>>>
export type GetVariantsResult = NonNullable<Awaited<ReturnType<typeof getVariants>>>
export type GetVersionsResult = NonNullable<Awaited<ReturnType<typeof getVersions>>>
export type GetOntologiesResult = NonNullable<Awaited<ReturnType<typeof getOntologies>>>
export type GetTermOntologiesResult = NonNullable<Awaited<ReturnType<typeof getTermOntologies>>>
export type GetDiscussionsResult = NonNullable<Awaited<ReturnType<typeof getDiscussions>>>
export type AddToDiscussionResult = NonNullable<Awaited<ReturnType<typeof addToDiscussion>>>
export type GetPingResult = NonNullable<Awaited<ReturnType<typeof getPing>>>
