/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import type {
  Terms
} from '../model'
import { customInstance } from '../mutator/custom-client';



  /**
 * @summary Get all terms
 */
export const getTerms = (
    
 ) => {
      return customInstance<Terms>(
      {url: `/get_terms`, method: 'GET'
    },
      );
    }
  
/**
 * @summary List all matching terms
 */
export const getMatchTerms = (
    term: string | undefined | null,
 ) => {
      return customInstance<Terms>(
      {url: `/search_term/${term}`, method: 'GET'
    },
      );
    }
  

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetTermsResult = NonNullable<Awaited<ReturnType<typeof getTerms>>>
export type GetMatchTermsResult = NonNullable<Awaited<ReturnType<typeof getMatchTerms>>>
