/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Swagger Mock Missing Endpoints
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  Organization,
  Organizations,
  Terms
} from '../model'

export const getLoginResponseMock = () => ((() => ({
                status: 200,
                token: "",
                username: ""
              }))())

export const getLogoutResponseMock = () => ((() => ({
                status: 200,
                token: "",
                username: ""
              }))())

export const getRegisterResponseMock = () => ((() => ({
                status: 200,
                token: "",
                username: ""
              }))())

export const getGetOrganizationResponseMock = () => ((() => ({
                name: "SPARC Anatomical Working Group",
                description : "The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) drive to map out the neural circuitry responsible for visceral control in higher vertebrates. The SPARC Anatomy Working Group (SAWG) is responsible for the integrity of anatomical knowledge in SPARC. In particular, it provides the relevant guidance and expertise about: Defining and naming anatomical terms, Maintaining ontologies of anatomical knowledge, Compiling and curating computable knowledge about multiscale routes pathways",
                creation_date: "01/01/2000",
                status: 200,
                message: "",
                id: "ilx_0101431",
                url: "sparc.science",
                author : "SPARC",
                terms : [{
                  name : "Brain",
                  description : "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon.",
                  id : "ilx_0101431",
                  prefixes: {
                    owl: "http://www.w3.org/2002/07/owl#",
                    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                    rdfs: "http://www.w3.org/2000/01/rdf-schema#",
                    xsd: "http://www.w3.org/2001/XMLSchema#",
                    xml: "http://www.w3.org/XML/1998/namespace",
                    "": "file:///ERROR/EMPTY/PREFIX/BANNED/",
                  },
                  triples: [
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "suprasegmental levels of nervous system",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "synganglion",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "suprasegmental structures",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                      "<http://uri.neuinfo.org/nif/nifstd/birnlex_796>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/ilx_0112784>",
                      "<http://uri.interlex.org/base/ilx_0102661>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/ilx_0112796>",
                      "<http://uri.interlex.org/base/ilx_0101901>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://purl.obolibrary.org/obo/IAO_0000115>",
                      "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                      "<http://purl.org/sig/ont/fma/fma50801>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "the brain",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/ilx_0112785>",
                      "<http://uri.interlex.org/base/ilx_0101999>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "rdfs:subClassOf",
                      "<http://uri.interlex.org/base/ilx_0108124>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "Encephalon",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "rdfs:label",
                      "Brain",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                      "<http://purl.obolibrary.org/obo/UBERON_0000955>",
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0101431>",
                      "rdf:type",
                      "owl:Class",
                    ],
                  ],
                },
                {
                  name : "Right vagus nerve",
                  description : "Right vagus nerve",
                  id : "ilx_0789705",
                  prefixes: {
                    "owl": "http://www.w3.org/2002/07/owl#",
                    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                    "xsd": "http://www.w3.org/2001/XMLSchema#",
                    "xml": "http://www.w3.org/XML/1998/namespace",
                    "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                  },
                  triples: [
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "<http://uri.interlex.org/base/ilx_0738400>",
                      "<http://uri.interlex.org/base/ilx_0793922>"
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "Right vagus"
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                      "<http://purl.org/sig/ont/fma/fma6219>"
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "rdfs:label",
                      "Right vagus nerve"
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "<http://uri.interlex.org/base/readable/synonym>",
                      "Right vagus nerve tree"
                    ],
                    [
                      "<http://uri.interlex.org/base/ilx_0789705>",
                      "rdf:type",
                      "owl:Class"
                    ]
                  ]
                }]
                
              }))())

export const getNewOrganizationResponseMock = () => ((() => ({
                status: 200,
                token: "",
                name: ""
              }))())

export const getGetOrganizationsResponseMock = () => ((() => [
                {
                  name: "SPARC Anatomical Working Group",
                  description : "The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) drive to map out the neural circuitry responsible for visceral control in higher vertebrates. The SPARC Anatomy Working Group (SAWG) is responsible for the integrity of anatomical knowledge in SPARC. In particular, it provides the relevant guidance and expertise about: Defining and naming anatomical terms, Maintaining ontologies of anatomical knowledge, Compiling and curating computable knowledge about multiscale routes pathways",
                  creation_date: "01/01/2000",
                  status: 200,
                  message: "",
                  id: "ilx_0101431",
                  url: "sparc.science",
                  author : "SPARC",
                  terms : [{
                    name : "Brain",
                    description : "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon.",
                    id : "ilx_0101431",
                    prefixes: {
                      owl: "http://www.w3.org/2002/07/owl#",
                      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
                      xsd: "http://www.w3.org/2001/XMLSchema#",
                      xml: "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/",
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental levels of nervous system",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "synganglion",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental structures",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://uri.neuinfo.org/nif/nifstd/birnlex_796>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112784>",
                        "<http://uri.interlex.org/base/ilx_0102661>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112796>",
                        "<http://uri.interlex.org/base/ilx_0101901>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://purl.obolibrary.org/obo/IAO_0000115>",
                        "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma50801>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "the brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112785>",
                        "<http://uri.interlex.org/base/ilx_0101999>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:subClassOf",
                        "<http://uri.interlex.org/base/ilx_0108124>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Encephalon",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:label",
                        "Brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.obolibrary.org/obo/UBERON_0000955>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdf:type",
                        "owl:Class",
                      ],
                    ],
                  },
                  {
                    name : "Right vagus nerve",
                    description : "Right vagus nerve",
                    id : "ilx_0789705",
                    prefixes: {
                      "owl": "http://www.w3.org/2002/07/owl#",
                      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                      "xsd": "http://www.w3.org/2001/XMLSchema#",
                      "xml": "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/ilx_0738400>",
                        "<http://uri.interlex.org/base/ilx_0793922>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma6219>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdfs:label",
                        "Right vagus nerve"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus nerve tree"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdf:type",
                        "owl:Class"
                      ]
                    ]
                  }]
                  
                },
                {
                  name: "SPARC Anatomical Working Group",
                  description : "The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) drive to map out the neural circuitry responsible for visceral control in higher vertebrates. The SPARC Anatomy Working Group (SAWG) is responsible for the integrity of anatomical knowledge in SPARC. In particular, it provides the relevant guidance and expertise about: Defining and naming anatomical terms, Maintaining ontologies of anatomical knowledge, Compiling and curating computable knowledge about multiscale routes pathways",
                  creation_date: "21/11/2020",
                  status: 200,
                  message: "",
                  id: "ilx_0101431",
                  url: "sparc.science",
                  author : "SPARC",
                  terms : [{
                    name : "Brain",
                    description : "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon.",
                    id : "ilx_0101431",
                    prefixes: {
                      owl: "http://www.w3.org/2002/07/owl#",
                      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
                      xsd: "http://www.w3.org/2001/XMLSchema#",
                      xml: "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/",
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental levels of nervous system",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "synganglion",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental structures",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://uri.neuinfo.org/nif/nifstd/birnlex_796>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112784>",
                        "<http://uri.interlex.org/base/ilx_0102661>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112796>",
                        "<http://uri.interlex.org/base/ilx_0101901>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://purl.obolibrary.org/obo/IAO_0000115>",
                        "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma50801>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "the brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112785>",
                        "<http://uri.interlex.org/base/ilx_0101999>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:subClassOf",
                        "<http://uri.interlex.org/base/ilx_0108124>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Encephalon",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:label",
                        "Brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.obolibrary.org/obo/UBERON_0000955>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdf:type",
                        "owl:Class",
                      ],
                    ],
                  },
                  {
                    name : "Right vagus nerve",
                    description : "Right vagus nerve",
                    id : "ilx_0789705",
                    prefixes: {
                      "owl": "http://www.w3.org/2002/07/owl#",
                      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                      "xsd": "http://www.w3.org/2001/XMLSchema#",
                      "xml": "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/ilx_0738400>",
                        "<http://uri.interlex.org/base/ilx_0793922>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma6219>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdfs:label",
                        "Right vagus nerve"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus nerve tree"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdf:type",
                        "owl:Class"
                      ]
                    ]
                  }]
                },
                {
                  name: "SPARC Anatomical Working Group",
                  description : "The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) drive to map out the neural circuitry responsible for visceral control in higher vertebrates. The SPARC Anatomy Working Group (SAWG) is responsible for the integrity of anatomical knowledge in SPARC. In particular, it provides the relevant guidance and expertise about: Defining and naming anatomical terms, Maintaining ontologies of anatomical knowledge, Compiling and curating computable knowledge about multiscale routes pathways",
                  creation_date: "08/06/2024",
                  status: 200,
                  message: "",
                  id: "ilx_0101431",
                  url: "sparc.science",
                  author : "SPARC",
                  terms : [{
                    name : "Brain",
                    description : "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon.",
                    id : "ilx_0101431",
                    prefixes: {
                      owl: "http://www.w3.org/2002/07/owl#",
                      rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      rdfs: "http://www.w3.org/2000/01/rdf-schema#",
                      xsd: "http://www.w3.org/2001/XMLSchema#",
                      xml: "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/",
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental levels of nervous system",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "synganglion",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "suprasegmental structures",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://uri.neuinfo.org/nif/nifstd/birnlex_796>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112784>",
                        "<http://uri.interlex.org/base/ilx_0102661>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112796>",
                        "<http://uri.interlex.org/base/ilx_0101901>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://purl.obolibrary.org/obo/IAO_0000115>",
                        "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma50801>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "the brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/ilx_0112785>",
                        "<http://uri.interlex.org/base/ilx_0101999>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:subClassOf",
                        "<http://uri.interlex.org/base/ilx_0108124>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Encephalon",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdfs:label",
                        "Brain",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.obolibrary.org/obo/UBERON_0000955>",
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0101431>",
                        "rdf:type",
                        "owl:Class",
                      ],
                    ],
                  },
                  {
                    name : "Right vagus nerve",
                    description : "Right vagus nerve",
                    id : "ilx_0789705",
                    prefixes: {
                      "owl": "http://www.w3.org/2002/07/owl#",
                      "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                      "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                      "xsd": "http://www.w3.org/2001/XMLSchema#",
                      "xml": "http://www.w3.org/XML/1998/namespace",
                      "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                    },
                    triples: [
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/ilx_0738400>",
                        "<http://uri.interlex.org/base/ilx_0793922>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                        "<http://purl.org/sig/ont/fma/fma6219>"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdfs:label",
                        "Right vagus nerve"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "<http://uri.interlex.org/base/readable/synonym>",
                        "Right vagus nerve tree"
                      ],
                      [
                        "<http://uri.interlex.org/base/ilx_0789705>",
                        "rdf:type",
                        "owl:Class"
                      ]
                    ]
                  }]
                }
              ])())

export const getGetSearchResultsResponseMock = (overrideResponse: any = {}): Terms => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({description: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), prefixes: {}, triples: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())))), ...overrideResponse})))

export const getGetHierarchyResultsResponseMock = (overrideResponse: any = {}): Terms => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({description: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), prefixes: {}, triples: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())))), ...overrideResponse})))

export const getGetMatchTermsResponseMock = () => ((() => [{
                name : "Brain",
                description : "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon.",
                id : "ilx_0101431",
                prefixes: {
                  owl: "http://www.w3.org/2002/07/owl#",
                  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  rdfs: "http://www.w3.org/2000/01/rdf-schema#",
                  xsd: "http://www.w3.org/2001/XMLSchema#",
                  xml: "http://www.w3.org/XML/1998/namespace",
                  "": "file:///ERROR/EMPTY/PREFIX/BANNED/",
                },
                triples: [
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "suprasegmental levels of nervous system",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "synganglion",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "suprasegmental structures",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                    "<http://uri.neuinfo.org/nif/nifstd/birnlex_796>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/ilx_0112784>",
                    "<http://uri.interlex.org/base/ilx_0102661>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/ilx_0112796>",
                    "<http://uri.interlex.org/base/ilx_0101901>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://purl.obolibrary.org/obo/IAO_0000115>",
                    "The part of the central nervous system contained within the cranium, comprising the forebrain, midbrain, hindbrain, and metencephalon. It is derived from the anterior part of the embryonic neural tube (or the encephalon). Does not include retina. (CUMBO)The rostral topographic division of the cerebrospinal axis, while the caudal division is the spinal cord. The usual criterion for distinguishing the two divisions in the adult is that the vertebrate brain lies within the skull whereas the spinal cord lies within the spinal (vertebral) column, although this is a difficult problem. (Swanson, 2014)",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                    "<http://purl.org/sig/ont/fma/fma50801>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "the brain",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/ilx_0112785>",
                    "<http://uri.interlex.org/base/ilx_0101999>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "rdfs:subClassOf",
                    "<http://uri.interlex.org/base/ilx_0108124>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "Encephalon",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "rdfs:label",
                    "Brain",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                    "<http://purl.obolibrary.org/obo/UBERON_0000955>",
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101431>",
                    "rdf:type",
                    "owl:Class",
                  ],
                ],
              },
              {
                name : "Right vagus nerve",
                description : "Right vagus nerve",
                id : "ilx_0789705",
                prefixes: {
                  "owl": "http://www.w3.org/2002/07/owl#",
                  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                  "xsd": "http://www.w3.org/2001/XMLSchema#",
                  "xml": "http://www.w3.org/XML/1998/namespace",
                  "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                },
                triples: [
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "<http://uri.interlex.org/base/ilx_0738400>",
                    "<http://uri.interlex.org/base/ilx_0793922>"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "Right vagus"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                    "<http://purl.org/sig/ont/fma/fma6219>"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "rdfs:label",
                    "Right vagus nerve"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "Right vagus nerve tree"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0789705>",
                    "rdf:type",
                    "owl:Class"
                  ]
                ]
              },
              {
                name : "includeForSPARC",
                description : "A relationship that binds a term to the required entities for the purposes required by SPARC",
                id : "ilx_0738400",
                prefixes: {
                  "owl": "http://www.w3.org/2002/07/owl#",
                  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                  "xsd": "http://www.w3.org/2001/XMLSchema#",
                  "xml": "http://www.w3.org/XML/1998/namespace",
                  "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                },
                triples: [
                  [
                    "<http://uri.interlex.org/base/ilx_0738400>",
                    "<http://purl.obolibrary.org/obo/IAO_0000115>",
                    "A relationship that binds a term to the required entities for the purposes required by SPARC, e.g., returning a term in response to a query for all relevant organ parts when it is not specified in the core ontology.  We view this as a temporary and practical solution.  At some points, all such terms will be contributed back to the core ontologies for proper engineering."
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0738400>",
                    "rdfs:label",
                    "includeForSPARC"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0738400>",
                    "rdf:type",
                    "owl:ObjectProperty"
                  ]
                ]
              },
              {
                name : "Cerebrospinal axis",
                description : "The hollow tubular division of the nervous system that lies in the median plane, dorsal to a notochord and flanked by a bilateral series of segmental muscles.It is the topographic division that corresponds to the vertebrate central nervous system.",
                id : "ilx_0101999",
                prefixes: {
                  "owl": "http://www.w3.org/2002/07/owl#",
                  "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                  "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
                  "xsd": "http://www.w3.org/2001/XMLSchema#",
                  "xml": "http://www.w3.org/XML/1998/namespace",
                  "": "file:///ERROR/EMPTY/PREFIX/BANNED/"
                },
                triples: [
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "<http://uri.interlex.org/base/readable/synonym>",
                    "CSA"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "<http://uri.interlex.org/tgbugs/uris/readable/hasExistingId>",
                    "<http://uri.neuinfo.org/nif/nifstd/nlx_158477>"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "rdf:type",
                    "owl:Class"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "<http://uri.interlex.org/base/ilx_0112785>",
                    "<http://uri.interlex.org/base/ilx_0107422>"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "<http://purl.obolibrary.org/obo/IAO_0000115>",
                    "The hollow tubular division of the nervous system that lies in the median plane, dorsal to a notochord and flanked by a bilateral series of segmental muscles.It is the topographic division that corresponds to the vertebrate central nervous system."
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "rdfs:label",
                    "Cerebrospinal axis"
                  ],
                  [
                    "<http://uri.interlex.org/base/ilx_0101999>",
                    "rdfs:subClassOf",
                    "<http://uri.interlex.org/base/ilx_0109835>"
                  ]
                ]
              }])())


export const getLoginMockHandler = (overrideResponse?: void) => {
  return http.post('*/operations/login', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getLoginResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getLogoutMockHandler = (overrideResponse?: void) => {
  return http.post('*/operations/logout', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getLogoutResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getRegisterMockHandler = (overrideResponse?: void) => {
  return http.post('*/operations/register', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getRegisterResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOrganizationMockHandler = (overrideResponse?: Organization) => {
  return http.get('*/operations/organization', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetOrganizationResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getNewOrganizationMockHandler = (overrideResponse?: Organization) => {
  return http.post('*/operations/organization', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getNewOrganizationResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetOrganizationsMockHandler = (overrideResponse?: Organizations) => {
  return http.get('*/operations/organizations', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetOrganizationsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetSearchResultsMockHandler = (overrideResponse?: Terms) => {
  return http.get('*/:group/search/:string', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetSearchResultsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetHierarchyResultsMockHandler = (overrideResponse?: Terms) => {
  return http.get('*/:group/query/transitive/:property/:start?depth', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetHierarchyResultsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetMatchTermsMockHandler = (overrideResponse?: Terms) => {
  return http.get('*/search_term/:term', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getGetMatchTermsResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}

export const getGetPingMockHandler = () => {
  return http.get('*/ping', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getSwaggerMockMissingEndpointsMock = () => [
  getLoginMockHandler(),
  getLogoutMockHandler(),
  getRegisterMockHandler(),
  getGetOrganizationMockHandler(),
  getNewOrganizationMockHandler(),
  getGetOrganizationsMockHandler(),
  getGetSearchResultsMockHandler(),
  getGetHierarchyResultsMockHandler(),
  getGetMatchTermsMockHandler(),
  getGetPingMockHandler()]
