export const API_CONFIG = {
    MOCK_API: {
        GET_ORGANIZATIONS: "/api/mock/organizations",
        GET_ORGANIZATION: "/api/mock/organization",
        GET_ORGANIZATION_TERMS: "/api/mock/organization/terms",
        GET_ORGANIZATION_CURIES: "/api/mock/organization/curies",
        GET_ORGANIZATION_ONTOLOGIES: "/api/mock/organization/ontologies",
        GET_VARIANTS: "/api/mock/variants",
        GET_VERSIONS: "/api/mock/versions",
        GET_CURIES: "/api/mock/curies",
        SEARCH_ALL: "/api/mock/search",
        PATCH_TERM: "/api/mock/patch-term",
        ADD_TERM: "/api/mock/add-term",
        BULK_EDIT_TERMS: "/api/mock/bulk-edit",
        GET_USER: "/api/mock/user",
        GET_EXISTING_IDS: "/api/mock/existing-ids",
        SIGNUP: "/api/mock/signup",
        GET_VARIANT_DISCUSSIONS: "/api/mock/variant-discussions",
        GET_TERM_DISCUSSIONS: "/api/mock/term-discussions",
        ADD_TO_TERM_DISCUSSION: "/api/mock/add-term-discussion",
        ADD_TO_VARIANT_DISCUSSION: "/api/mock/add-variant-discussion",
    },
    REAL_API: {
        GET_ENDPOINTS_ILX: "/api/real/endpoints-ilx",
        PATCH_ENDPOINTS_ILX: "/api/real/patch-endpoints-ilx",
        SIGNIN: "/u/ops/user-login",
        ORCID_SIGNIN: "/u/ops/orcid-login",
        NEWUSER_ILX: "/u/ops/user-new",
        NEWUSER_ORCID: "/u/ops/orcid-new",
        USER_SETTINGS: "/priv/settings",
        CREATE_NEW_ORGANIZATION: "/priv/org-new",
        CREATE_NEW_ENTITY: "/priv/entity-new",
        CREATE_NEW_ONTOLOGY: "/{groupname}/ontologies/uris/{filename}/spec",
        API_NEW_TOKEN: "/priv/api-token-new",
        API_RETRIEVE_TOKEN: "/priv/api-tokens",
        GET_ORGANIZATIONS: "/priv/role-other",
        LOGOUT: "/priv/logout",
        USER_RECOVER: "/u/ops/user-recover",
        CHECK_ENTITY: "/priv/entity-check",
        USER_ROLE: "/priv/role",
        PULL_NEW: "/priv/pull-new",
        PULLS: "/pulls",
        PASSWORD_CHANGE: "/priv/password_change",
        ORG_TERMS: "/contributions",
        ORG_ONTOLOGIES: "/ontologies",
        ORG_CURIES: "/curies"
    },
    SESSION_DATA: {
        SETTINGS: "settings",
        COOKIE: "session",
    },
    OLYMPIAN_GODS : "https://uri.olympiangods.org",
    BASE_SCICRUNCH_URL: "/api/elasticsearch?apikey=",
    SCICRUNCH_KEY: import.meta.env.VITE_SCICRUNCH_API_KEY,
    BASE_URL: window.location.origin,
    INTERLEX_URL: "http://uri.interlex.org",
    // BASE_URL: import.meta.env.MODE === "production" ? "https://uri.olympiangods.org" : window.location.origin,
};
